---
title: "FinalProject"
author: "Allison Lettiere"
date: "5/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
headers = read.csv("SpotifyFeatures.csv", header = F, nrows = 1, as.is = T)
spotifyFeatures = read.csv("SpotifyFeatures.csv", skip = 5)
colnames(spotifyFeatures) = headers
```

```{r}
library(corrplot)
library(dplyr)
library(sets)
quantitativeFeatures = subset(spotifyFeatures, select=c(acousticness, danceability, duration_ms, energy, instrumentalness, liveness, loudness, speechiness, tempo, valence))


row.names(quantitativeFeatures) = as.list(spotifyFeatures$track_id)
cor1 = cor(quantitativeFeatures, use = "complete.obs")
corrplot.mixed(cor1, lower.col = 'black')

##Bootstrap modeling of the correlation between energy and the other variables
M = 100
results = matrix(0, nrow = M, ncol = ncol(quantitativeFeatures))
confidenceIntervals = list(rep(0, ncol(quantitativeFeatures)))
for(i in 1:ncol(quantitativeFeatures)){
  for(j in 1:M){
    sam = quantitativeFeatures[sample.int(nrow(quantitativeFeatures),replace = T),] #sample data with replacement
    results[j, i] = cor(sam[,i],sam[,4], method = "spearman")
  }
  hist(results[,i], xlab = paste("Correlation Between energy and ", colnames(quantitativeFeatures)[i]), main = paste("Bootstrap Correlation Test"))
  confidenceIntervals[i] = tuple((quantile(results[,i], probs =c(.05, .95))))
}
confidenceIntervals
library(usdm)
vif(quantitativeFeatures)
vifcor(quantitativeFeatures, th=0.8)
```

```{r}
library(factoextra)
reducedFeatures = subset(spotifyFeatures, select=c(acousticness, danceability, duration_ms, instrumentalness, liveness, loudness, speechiness, tempo, valence))

pca = prcomp(na.omit(reducedFeatures), center = TRUE, scale = TRUE)
summary(pca)

#https://rpubs.com/JanpuHou/278584
pcaCharts <- function(x) {
    x.var <- x$sdev ^ 2
    x.pvar <- x.var/sum(x.var)
    print("proportions of variance:")
    print(x.pvar)
    
    par(mfrow=c(2,2))
    plot(x.pvar,xlab="Principal component", ylab="Proportion of variance explained", ylim=c(0,1), type='b')
    plot(cumsum(x.pvar),xlab="Principal component", ylab="Cumulative Proportion of variance explained", ylim=c(0,1), type='b')
    screeplot(x)
    screeplot(x,type="l")
    par(mfrow=c(1,1))
}
pcaCharts(pca)

fviz_pca_var(pca)

fviz_screeplot(pca, addlabels = TRUE, ylim = c(0, 50))

res.var <- get_pca_var(pca)
res.var$contrib  
res.var$cor 
```

```{r}
library(cluster)
library(diceR)

reducedFeatures = subset(spotifyFeatures, select=c(acousticness, danceability, instrumentalness, liveness, loudness, speechiness, tempo, valence))
#reducedFeatures = scale(reducedFeatures)
rownums = sample(nrow(reducedFeatures), 1000, replace = FALSE)
df = reducedFeatures[rownums, ]

##Gap Statistic
gap_stat = clusGap(df, FUN = kmeans, K.max = 50, B = 50)
plot(gap_stat)

##Using the K from the value that yield the best gap statistic
max = which(gap_stat$Tab[, "gap"] == max(gap_stat$Tab[, "gap"])); max
km1 = kmeans(reducedFeatures, max, iter.max = 10000, algorithm="MacQueen")
pvalue1 = sigclust(reducedFeatures, nsim = 10, k = max)
pvalue1
plotcluster(reducedFeatures, km1$cluster)
clusplot(reducedFeatures, km1$cluster, main = "Cluster plot", color=TRUE, shade=TRUE, labels=max, lines=0)
plot(reducedFeatures, col = km1$cluster, pch = 19, frame = FALSE, main = "K-means with K from Best Gap Statistic")
points(km$centers, col = 1:max, pch = 8, cex = 3)

##Using the K from the maximum standard error computation
k = maxSE(gap_stat$Tab[, "gap"], gap_stat$Tab[, "SE.sim"], method="Tibs2001SEmax")
km2 = kmeans(reducedFeatures, k, iter.max = 10000, algorithm="MacQueen")
pvalue2 = sigclust(reducedFeatures, nsim = 10, k = k)
pvalue2
plotcluster(reducedFeatures, km2$cluster)
clusplot(reducedFeatures, km2$cluster, main = "Cluster plot", color=TRUE, shade=TRUE, labels=k, lines=0)
plot(reducedFeatures, col = km2$cluster, pch = 19, frame = FALSE, main = "K-means with K from maxSE computation")
points(km$centers, col = 1:k, pch = 8, cex = 3)

##Finding a K-value using the Bootstrap-t interval
theta.hat = max
se.theta.hat = maxSE(gap_stat$Tab[, "gap"], gap_stat$Tab[, "SE.sim"], method="Tibs2001SEmax")

z.star =function(x){
  x.star =sample(x, size = 100,replace = TRUE)
  
  cg = clusGap(x.star, FUN = kmeans, K.max = 50, B = 10)
  theta.hat.star = which(cg$Tab[, "gap"] == max(cg$Tab[, "gap"]))
  se.theta.hat.star = maxSE(cg$Tab[, "gap"], cg$Tab[, "SE.sim"], method="Tibs2001SEmax")

  z.star.b = abs(theta.hat.star-theta.hat)/(se.theta.hat.star)
  return(z.star.b)
}

B = 100
z.star.B =replicate(B, z.star(df))

alpha = .025
k =ceiling((B+1)*alpha)
t.hat.one.minus.alpha =sort(z.star.B,decreasing = TRUE)[k]
t1 = t.hat.one.minus.alpha; 

t.hat.alpha =sort(z.star.B,decreasing = TRUE)[B+1-k]
t2 = t.hat.alpha; 

ci.bootstrap.t =round(theta.hat-c((t1), (t2))*se.theta.hat, digits = 4)
ci.bootstrap.t


bootk = 25 
km3 = kmeans(reducedFeatures, bootk, iter.max = 10000, algorithm="MacQueen")
pvalue3 = sigclust(reducedFeatures, nsim = 10, k = bootk)
pvalue3
plotcluster(reducedFeatures, km3$cluster)
clusplot(reducedFeatures, km3$cluster, main = "Cluster plot", color=TRUE, shade=TRUE, labels=bootk, lines=0)
plot(reducedFeatures, col = km3$cluster, pch = 19, frame = FALSE, main = "K-means with K from Bootstrap t test")
points(km$centers, col = 1:bootk, pch = 8, cex = 3)
```

```{r}
library(fpc)
reducedFeatures = subset(spotifyFeatures, select=c(acousticness, danceability, instrumentalness, liveness, loudness, speechiness, tempo, valence))

rownums = sample(nrow(reducedFeatures), 1000, replace = FALSE)
dfnSelect = reducedFeatures[rownums, ]

clusterNumber = nselectboot(dfnSelect,B=10,distances=inherits(data,"dist"), classification="averagedist",krange=5:50, count = FALSE, clustermethod = kmeansCBI)
clusterNumber$kopt
plot(clusterNumber$stabk, ylab = "mean instability values for numbers of clusters", xlab = "Number of Clusters")

pk1 <- pamk(dfnSelect,krange=5:50,criterion="asw")
plot(pk1$pamobject)
plot(pk1$crit, ylab = "criterion value", xlab = "Number of Clusters")
pk1$nc
```

```{r, warning=FALSE}
kValue = 25
km = kmeans(reducedFeatures, kValue, iter.max = 10000, algorithm="MacQueen")
fviz_cluster(km, data = reducedFeatures)

km.flexclust <- as.kcca(km, data=reducedFeatures)
km.flexclust

rownames(quantitativeFeatures) = paste(spotifyFeatures$track_name, substr(spotifyFeatures$track_id, 1 ,4))
df = quantitativeFeatures[sample(nrow(quantitativeFeatures), 100), ]
fviz_cluster(km, data = df)

kccaCluster = kcca(reducedFeatures, kValue, family=kccaFamily("kmeans"))
centroids = parameters(kccaCluster)

shadowPlot = shadow(kccaCluster)
plot(shadowPlot)

cc <- cclust(reducedFeatures, kValue, save.data=TRUE)
plot(cc)
silhouettePlot = Silhouette(cc)
plot(silhouettePlot)

stripes(kccaCluster)
```


```{r}
finalPlaylists = rep(list(), length(playlistRequests))
library(Momocs)
library(mgcv)
library(class)
library(BBmisc)
```

Approach #1
```{r}
for(i in 1:(length(playlistRequests)/5)){
  finalSongs <- rep(0, 5)
  for(j in 1:5){
    songId = playlistRequests[i + (j - 1)]
    index = which(spotifyFeatures$track_id==songId, arr.ind=TRUE)
    prd = data.frame(spotifyFeatures$acousticness[index], spotifyFeatures$danceability[index], 
                       spotifyFeatures$instrumentalness[index], spotifyFeatures$liveness[index], spotifyFeatures$loudness[index],
                       spotifyFeatures$speechiness[index], spotifyFeatures$tempo[index], spotifyFeatures$valence[index])
    colnames(prd) = c("acousticness", "danceability", "instrumentalness", "liveness", "loudness", "speechiness", "tempo", "valence")

    pred.flexclust <- predict(km.flexclust, newdata=prd)
    data_clus <- reducedFeatures[km$cluster == pred.flexclust,]

    newSong = sample(data_clus, 1)
    newSongIndex = which(spotifyFeatures$acousticness == newSong[1] & spotifyFeatures$danceability == newSong[2])
    nameAndArtist = paste(spotifyFeatures$track_name[newSongIndex], spotifyFeatures$artist_name[newSongIndex], sep = "-")
    finalSongs[j] = nameAndArtist
  }
  finalPlaylists[[i]] = finalSongs
}

finalPlaylists
```

Approach #2
```{r}
for(i in 1:3){
#for(i in 1:(length(playlistRequests)/5)){
  finalSongs <- rep(0, 5)
  for(j in 1:5){
    songId = playlistRequests[i + (j - 1)]
    index = which(spotifyFeatures$track_id==songId, arr.ind=TRUE)
    prd = data.frame(spotifyFeatures$acousticness[index], spotifyFeatures$danceability[index], 
                       spotifyFeatures$instrumentalness[index], spotifyFeatures$liveness[index], spotifyFeatures$loudness[index],
                       spotifyFeatures$speechiness[index], spotifyFeatures$tempo[index], spotifyFeatures$valence[index])
    colnames(prd) = c("acousticness", "danceability", "instrumentalness", "liveness", "loudness", "speechiness", "tempo", "valence")

    pred.flexclust <- predict(km.flexclust, newdata=prd)
    data_clus <- reducedFeatures[km$cluster == pred.flexclust,]

    fit <- gam(danceability ~ s(acousticness, bs = 'cr', fx = FALSE) + s(instrumentalness, bs = 'cr', fx = FALSE) + s(liveness, bs = 'cr', fx = FALSE) + s(loudness, bs = 'cr', fx = FALSE) + s(speechiness, bs = 'cr', fx = FALSE) + s(tempo, bs = 'cr', fx = FALSE) + s(valence, bs = 'cr', fx = FALSE), data = data_clus)
    pred <- predict.gam(fit, prd)
    newSongIndex = which.min(abs(fit$fitted.values-as.vector(pred)))
    nameAndArtist = paste(spotifyFeatures$track_name[newSongIndex[1]], spotifyFeatures$artist_name[newSongIndex[1]], sep = "-")
    finalSongs[j] = nameAndArtist
  }
  finalPlaylists[[i]] = finalSongs
}

finalPlaylists
```

Approach #3
```{r}
for(i in 1:(length(playlistRequests)/5)){
  finalSongs <- rep(0, 5)
  for(j in 1:5){
    songId = playlistRequests[i + (j - 1)]
    index = which(spotifyFeatures$track_id==songId, arr.ind=TRUE)
    prd = data.frame(spotifyFeatures$acousticness[index], spotifyFeatures$danceability[index], 
                       spotifyFeatures$instrumentalness[index], spotifyFeatures$liveness[index], spotifyFeatures$loudness[index],
                       spotifyFeatures$speechiness[index], spotifyFeatures$tempo[index], spotifyFeatures$valence[index])
    colnames(prd) = c("acousticness", "danceability", "instrumentalness", "liveness", "loudness", "speechiness", "tempo", "valence")

    pred.flexclust <- predict(km.flexclust, newdata=prd)
    data_clus <- reducedFeatures[km$cluster == pred.flexclust,]
    
    #Compute all the pairwise dissimilarities (distances) between observations in the data set.
    gower_dist = daisy(rbind(data_clus, prd), metric = "gower", stand = TRUE, warnBin = FALSE, warnAsym = FALSE, warnConst = FALSE)
    gower_mat <- as.matrix(gower_dist)
    newSongIndex = rownames(data_clus[which(gower_mat == min(gower_mat[-1]), arr.ind = TRUE)[1, ], ])[1]
    nameAndArtist = paste(spotifyFeatures[newSongIndex,]$track_name, spotifyFeatures[newSongIndex,]$artist_name, sep = "-")
    finalSongs[j] = nameAndArtist
  }
  finalPlaylists[[i]] = finalSongs
}

finalPlaylists
```

Approach #4
```{r}
for(i in 1:(length(playlistRequests)/5)){
  finalSongs <- rep(0, 5)
  for(j in 1:5){
    songId = playlistRequests[i + (j - 1)]
    index = which(spotifyFeatures$track_id==songId, arr.ind=TRUE)
    prd = data.frame(spotifyFeatures$acousticness[index], spotifyFeatures$danceability[index], 
                       spotifyFeatures$instrumentalness[index], spotifyFeatures$liveness[index], spotifyFeatures$loudness[index],
                       spotifyFeatures$speechiness[index], spotifyFeatures$tempo[index], spotifyFeatures$valence[index])
    colnames(prd) = c("acousticness", "danceability", "instrumentalness", "liveness", "loudness", "speechiness", "tempo", "valence")

    pred.flexclust <- predict(km.flexclust, newdata=prd)
    data_clus <- reducedFeatures[km$cluster == pred.flexclust,]

    #Add the new point to the cluster and then choose the point that is closest to the updated centroid
    newClust = rbind(data_clus, prd)
    kme <- kmeans(newClust, 1, algorithm="MacQueen")
    centroid = kme$centers
    minDistance = 100000
    minIndex = 0
    for(i in 1:length(data_clus)){
      distance =(sqrt((data_clus$acousticness[i])^2 + (centroid[1])^2)
            + sqrt((data_clus$danceability[i])^2 + (centroid[2])^2)
            + sqrt((data_clus$instrumentalness[i])^2 + (centroid[3])^2)
            + sqrt((data_clus$liveness[i])^2 + (centroid[4])^2)
            + sqrt((data_clus$loudness[i])^2 + (centroid[5])^2)
            + sqrt((data_clus$speechiness[i])^2 + (centroid[6])^2)
            + sqrt((data_clus$tempo[i])^2 + (centroid[7])^2)
            + sqrt((data_clus$valence[i])^2 + (centroid[8])^2))
      if(distance < minDistance){
        minDistance = distance
        minIndex = i
      }
    }
    newSongIndex = minIndex
    nameAndArtist = paste(spotifyFeatures[newSongIndex,]$track_name, spotifyFeatures[newSongIndex,]$artist_name, sep = "-")
    finalSongs[j] = nameAndArtist
  }
  finalPlaylists[[i]] = finalSongs
}

finalPlaylists
```

```{r}
jessicay = c("6tdAmfHEd4cXEkNbCMgOP9", "2Fxmhks0bxGSBdJ92vM42m", "4SBVWkRIMJ6WBCYPvr5Bwr", "56dDonzTxrZKWuVDqUOYGd", "3c6afiysmB7OnxQzzSqRfD")
brycej = c("4QnKrqFiQwzKXOJ5sOk53u", "7yCqehT9dKACTFy7YugP0J", "7jKUnzzOGhAlPjr7LkIUlE", "05KOgYg8PGeJyyWBPi5ja8", "0z5ZPs57J2KERwM1tBM2GF")
aarthip = c("6uAm7pG66O1XesXS9bpHSF", "2Yer0p7uB2lVBUAtANuuQp", "41v7qDGXurEGgkMQWOk7hP", "0rTV5WefWd1J3OwIheTzxM", "3UDXkdQquqCEAJdNAsA1wO")
amandam1 = c("3HVWdVOQ0ZA45FuZGSfvns", "6LsAAHotRLMOHfCsSfYCsz", "20kzkNm5JLq6Yv1rGPVjtq", "4PkIDTPGedm0enzdvilLNd", "5MvLsT03RBp67RLoeISCdl")
andreab = c("2A69wys3S9uiPSmn6UZWJn", "6MBUUSIWCzaXW4q58Ktrv9", "30MM5jWpUmOxtTNd9Ey5LZ", "6arLnfArtdWKOcCYzDd4rS", "5Z19ylxppfnfdP4JH0u8oj")
jjr = c("4NN6N5TxBO5k9uqu0W4gfQ", "3SZqA7rQvROJsCbUu2v0xa", "1wJRveJZLSb1rjhnUHQiv6", "5jyyPsIGM2yqkZN9R3TmvN", "3XiNC94b4Tq1xwv70sQJGN")
kyleek = c("1DqdF42leyFIzqNDv9CjId", "2oENJa1T33GJ0w8dC167G4", "6u7jPi22kF8CTQ3rb9DHE7", "3cfOd4CMv2snFaKAnMdnvK", "6X5OFBbrsHRsyO1zP7udgr")
samm = c("6PlrGEPaisOqBiDlwW6Ic0", "3SZqA7rQvROJsCbUu2v0xa", "4cTm3Ev9bUvy4ChJjB1nhl", "1DUSuNhF8P5vUGNPpQiZa5", "43zdsphuZLzwA9k4DJhU0I")
gabbyc = c("3SZqA7rQvROJsCbUu2v0xa", "2U2Z1IXnmJIvlknWizFykZ", "6ho0GyrWZN3mhi9zVRW7xi", "3ylDbnvTHm3fWKJPJ6N6ur", "4ADsYu1V5CpFLXNve7iK4Z")
richardl1 = c("27IZXTdeGYjU6m5lTyDpmr", "7FWhvGFDMGo3BkuSI00rOi", "30SjdIdTMhBSe33nFnBFkC", "1r1fPuhj9H4VdXr7OK6FL5", "6L4mj0E16XEcSScIlB4x1l")
amandam2 = c("22oEJW6r2rMb9z4IntfyEa", "2Sm43une5m0vCKh4Rr6VhW", "5Xq7KPZSONkhHx6DFTAbTz", "0rTV5WefWd1J3OwIheTzxM", "3y3brCCecHC3Db18aIOnny")
andrese = c("4HMJ7QfHumQFkgClS0B8vU", "6QiLjKjMtPqoNdIlbqiIqv", "3FCto7hnn1shUyZL42YgfO", "0kIpcu3DQacQObHVyra9Jx", "3CCxL8R4wxfrGKqAmprgQi")
zoev = c("3B8Tx2eKzZ1u6bPnozOL1h", "7hDVYcQq6MxkdJGweuCtl9", "2QrXzOqLCVDRZHkToA0tSR", "6RIbDs0p4XusU2PZSiDgeZ", "6RIbDs0p4XusU2PZSiDgeZ")
ruthl = c("0NeJjNlprGfZpeX2LQuN6c", "6yM488yghMJP9bJnwZKyJT", "67LgGRNGmLw8tqJ7QGsPgW", "6dwkFmLUz6hx2CZG2EqLol", "2pJZ1v8HezrAoZ0Fhzby92")
inesn1 = c("3Lq4VAO0gwfhMXy4GSlHWd", "2WcR4C24997JVMwlX5guPZ", "0UlwTmT01jdFp3BaofARtU", "3TgEGPkT2iQ8U2kW6IlIeU", "1A32qMUaZfC4owBvFTHdZm")
nevc = c("0OGNtqKkjI7FCE9HZ4Khgo", "5Qel1sTrU4LM8HlJSPT2jd", "3E6iea9uEmB7gRru4lyP6h", "3TpXajg1nKzG3ngc9tBwrD", "5NijSs5dAwaIybq1GaRTIe")
skylart = c("5jyyPsIGM2yqkZN9R3TmvN", "6vMpPxLV0F5Diwcs6awI1Z", "3rDuYJzkBZw9jbbrRatwWu", "46HZ8l9wPo9JNsk7dZLamb", "7kQkmyoHCEqwe7QwDbkSXM")
saurenk = c("5mAbeNmPiyJ089q3eptg8P", "7eCDIw52Kbk8LGsCbTGbjY", "4Hk2SfFH6tv3Sd8NZt8Als", "5HllOy0J5LuH96EzMLGCPe", "33TWAlDSc32np6U9FDjiZN")
mimami = c("6sH7t53KqAP7RvO2slI2kv", "4HMJ7QfHumQFkgClS0B8vU", "2eHFk44RlGGfcJhYioirFR", "0lYBx37mRl0dbP7gF1yzh5", "0gjhhuqKxswtR1KzYSpSfd")
inesn2 = c("3zl7j5ua8mF4JDYuxrfo01", "7IWkJwX9C0J7tHurTD7ViL", "5PuY7F2jpk1yuD3ZNvzT85", "0lYBx37mRl0dbP7gF1yzh5", "0gjhhuqKxswtR1KzYSpSfd")
brycej2 = c("6ScJMrlpiLfZUGtWp4QIVt", "5G3UfEFiR4MUqkC8ETbzeR", "1jQsKN68yE94tMYml0wHMd", "5OCJzvD7sykQEKHH7qAC3C", "4uTvPEr01pjTbZgl7jcKBD")
valeria = c("5Qel1sTrU4LM8HlJSPT2jd", "2IRZnDFmlqMuOrYOLnZZyc", "11cDEev79fPKi6uJCjUhu8", "3A2yGHWIzmGEIolwonU69h", "7KwZNVEaqikRSBSpyhXK2j")
richardl2 = c("11dFghVXANMlKmJXsNCbNl", "3v9vIO8GfLbh2b0lWYttq6", "2KSSbWLAWSzaso01DEP32W", "41X9To0bQ4fpoSRri4NHiI", "0lP4HYLmvowOKdsQ7CVkuq")
juann = c("7jJsme36M90Cn6aYYC2l3t", "6C7RJEIUDqKkJRZVWdkfkH", "5ujh1I7NZH5agbwf7Hp8Hc", "4AYFCPg6DqR3d8YkdDTJJM", "2tQM1BUrXp2kqOM6mN11TC")
richardl3 = c("2qTy3hGSbxoSenKmlKGHFw", "0ZK8TGOsngrstVPsnrHbK1", "3VQSFTkbM2acvhwzkWztyM", "70x1x9NbSJJXkrgvIyyAVX", "7BCFYW9bxY74FhoyTdnsdH")
beatricef = c("4I5uWfaZIrkKCHrbO7eLMV", "1dJuteDIOkGfDSN7zPkzNv", "3dB42OEuVNiktvt3V5JRVI", "3DFBLpTc2KkuTTNDFg5ziF", "3s71tbgmSN9TfJLj4D18Mt")
alexandrah = c("23cj0rlc0UtTBaCg60VCkm", "2kG5litgxXvx6ZRgwO1v7W", "5esPpmrM2AsyDVgOKzWQwU", "4i13Vno2UPtn6kp2Ge9N2J", "0u0CceRGiKJM2wjXuHqkY8")
maiab = c("5kXDF4OmM5COyeo6z97nEk", "7aQeWViSfRWSEwtJD86Eq0", "5I7sGubUsKo4mVJpBoSVUr", "41cpvQ2GyGb2BRdIRSsTqK", "5ClqcvP4dYDDX6Zv3jPQD1")
gabea = c("5jd6XPyXSY4jQVG3SlXP1b", "4j9HBb9EShsJJ0EmQy8mgz", "6cG99KcHVOlmQOiYcu6cjb", "70pZIQqQ37SrNCADx0FiPN", "5ZHtJESnGmQNUo0AmBm4rN")
nickor = c("7bih7gVfK4zhAZcPAKpv5s", "17qyE3zCNdfOKmH3SXMwFX", "53jbdPQBaH6WaQvW0zmGBs", "4U4hey6H02kTMjVqw6dNh8", "1wsLHgXJ4SKIfd5ePSX1hD")
liaml = c("6HbGKJJqQ67K2TwzOndeTj", "4v1P7JCjehbg5TmLQo2mFy", "4Pyu35awSdHMHwLVtyyDnp", "1pF74yw15wXk12A1NPVWHD", "3NgyTfa2nTddA0VYzB44Iv")
jupip = c("6gKmuFhqEYmHf7ojbanTEg", "5iSEsR6NKjlC9SrIJkyL3k", "7cPO2IPraPDlGIguekShlV", "6ya8ejoKgw906Y8LWclqrp", "6uSSupG4TMu3vW8QgynAB6")
caroq = c("3RGM5AOCriBKii710ilEyP", "7p3XAxYOxflnVHHrotNizM", "0onslUNmSLDkuYaideYWir", "4U5ovGD4My7MOISvUEtYaf", "13jLiEg5wdMXuJzXXnRcnj")
gungukk = c("7dhyhMtWWJNYWmE4N5XiEA", "4CVOUJki8YUWol3jhLphgs", "6JyEh4kl9DLwmSAoNDRn5b", "4QtiVmuA88tPQiCOHZuQ5b", "1geovaCdfs5fSa4NNgFPVe")
kareem = c("5BoDFGTXZ8j5muc6Sb2jMz", "5pjWzUc1tVcewUTdDJd6Ce", "2dGXDL8P7ibb3uPdQ4ybuM", "3kBofOTKMUZ62a311eUwvx", "2drEUEg0TYQR6dDEHkpuPE")
ozan = c("5sCab5LlHPDB6NjvrZMwdX", "5jd6XPyXSY4jQVG3SlXP1b", "45R3FO8qwZcc9PwssP8Kaf", "3VwZqgfrM3xb1usuLprkTu", "0kFmWmvqQQzkFdwWlqza0a")
amar = c("23bqONDHbIwWZI1hQ75f4n", "3IT3klVvei2oWqjMHOv0uP", "60GA0yEMtXVc0JRpiDco6j", "4ThyHM57HG7pnLudis9b0M", "1CTkP74gXT4H96ppnholgU")
aprilb = c("3HVWdVOQ0ZA45FuZGSfvns", "22NN4BS1AlqVbyKIWExgON", "7vfaRUaFBDwENwa3tzJY64", "0HLWvLKQWpFdPhgk6ym58n", "30MM5jWpUmOxtTNd9Ey5LZ")
alexb = c("1dePmx9UxOVUsA4iSLCmIL", "0rTV5WefWd1J3OwIheTzxM", "52u48kvcn7fdhidNvRqEga", "7uldU4FkY6ZrYmpTC9Zp6U", "6cvRSOoJKvQwS0oDt0TePP")
caseyb = c("77hjM9bMmgfTGJXv14UFmi", "7iDa6hUg2VgEL1o1HjmfBn", "3ksmU0DaEUMEVzx5V6cc3z", "6u7jPi22kF8CTQ3rb9DHE7", "1OlDnyauZ0kTdD7AhzoNJC")
yvese = c("2fl0B0OaXjWbjHCQFx2O8W", "3pjUyVbFmM96tYhSaKJwTt", "3quQ7t4De0JV36sDuJhxTO", "2RPbEp0DyBVlkRvvYKopO7", "5DpiEEjTiQp1P1eJeduSR2")
emilyr = c("2Fxmhks0bxGSBdJ92vM42m", "2hloaUoRonYssMuqLCBLTX", "6kPJZM97LwdG9QIsT7khp6", "7b1WVMX0FShcPWct8ca7ma", "6rrTr2HEAzlpC4KWZxF3S1")
ademia = c("7wlcweEsneQgizqNOrUqJE", "5BSbdSiYKy8PCyUPAlWM5i", "68d6ZfyMUYURol2y15Ta2Y", "0T54ZCylSgBsGpvjWCcteB", "5X5XhvErlZwcy9Mj0O2aVV")
alexr = c("6b2oQwSGFkzsMtQruIWm2p", "3jJuBdO5rrtDufNAf76V1x", "6VJESmw3puw9eFpmglP2dM", "5kqIPrATaCc2LqxVWzQGbk", "2M9ro2krNb7nr7HSprkEgo")
kayla = c("01MO5Ib9mCG7srUhZl52BA", "5EyR6C5JvXzPlOMzU9A2GS", "6FWminmVdcErmcXOk81wMx", "4WYwP4V2SGCUXJGEha0ODM", "1US5HsLPV7riBx9RSCf4yO")
samd = c("4Vw3UGCAUQetVTmNdh6W5d", "7LikBkHerFGZ58QHVOKp1t", "3UReTN3heQsznBG8edEcTU", "5YTzmYWaMCnSBtCodjtxn7", "4mrB2Y8HB8SdT566tomnUx")
tiffany = c("6VwBbL8CzPiC4QV66ay7oR", "6rPO02ozF3bM7NnOV4h6s2", "6VObnIkLVruX4UVyxWhlqm", "6it15CsDlkqB7N4lF0C1qM", "2KvHC9z14GSl4YpkNMX384")
allan = c("2QjOHCTQ1Jl3zawyYOpxh6", "1D2L6MefbXon28PzIk9I3r", "0LQ1J0BCzA2qnAgp9MkkNE", "1fewSx2d5KIZ04wsooEBOz", "0NA5xAtDra50d0Lfs2uvoh")
aja = c("0g21KZ1XJuhwexWPLpuEt1", "4UIAJ1WnUvAPPdkzq2rn1i", "6ho0GyrWZN3mhi9zVRW7xi", "2tVzoSuPQpZ1yY7HHnXw7B", "13jLiEg5wdMXuJzXXnRcnj")
camilav = c("7n1940b6kHcaEewFSZXnXa", "7ef4DlsgrMEH11cDZd32M6", "6FRLCMO5TUHTexlWo8ym1W", "2ZxTjs4EdJl4Y9YByIiNoo", "5uCax9HTNlzGybIStD3vDh")

playlistRequests = c(jessicay, brycej, aarthip, amandam1, andreab, jjr, kyleek, samm, gabbyc, richardl1, amandam2, andrese, zoev, ruthl, inesn1, nevc, skylart, saurenk, mimami, inesn2, brycej2, valeria, richardl2, juann, richardl3, beatricef, alexandrah, maiab, gabea, nickor, liaml, jupip, caroq, gungukk, kareem, ozan, amar, aprilb, alexb, caseyb, yvese, emilyr, ademia, alexr, kayla, samd, tiffany, allan, aja, camilav)
```
