{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reading File Data!\n",
      "\n",
      "['NULL', 'Pop', 'Alternative', 'Blues', 'R&B', 'World', 'Dance', 'Soul', 'Hip-Hop', 'Reggae', 'Country', 'Electronic', 'Rock', 'Comedy', 'Folk', 'Jazz', 'Ska', 'Rap', 'Reggaeton', 'Indie', 'Classical', 'Soundtrack', 'Opera', 'Movie', 'A Capella']\n",
      "25\n",
      "here\n",
      "Pop\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pop\n",
      "6022\n",
      "Alternative\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Alternative\n",
      "5300\n",
      "Blues\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Blues\n",
      "3295\n",
      "R&B\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "R&B\n",
      "4869\n",
      "World\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "World\n",
      "8038\n",
      "Dance\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dance\n",
      "8298\n",
      "Soul\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Soul\n",
      "5058\n",
      "Hip-Hop\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hip-Hop\n",
      "2285\n",
      "Reggae\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reggae\n",
      "8711\n",
      "Country\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Country\n",
      "7325\n",
      "Electronic\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Electronic\n",
      "9149\n",
      "Rock\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Rock\n",
      "2070\n",
      "Comedy\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Comedy\n",
      "9676\n",
      "Folk\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Folk\n",
      "7801\n",
      "Jazz\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Jazz\n",
      "8144\n",
      "Ska\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Ska\n",
      "8022\n",
      "Rap\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Rap\n",
      "4519\n",
      "Reggaeton\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reggaeton\n",
      "8537\n",
      "Indie\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Indie\n",
      "2781\n",
      "Classical\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Classical\n",
      "9250\n",
      "Soundtrack\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Soundtrack\n",
      "8967\n",
      "Opera\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Opera\n",
      "7891\n",
      "Movie\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Movie\n",
      "7555\n",
      "A Capella\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.\n",
      "  FutureWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A Capella\n",
      "119\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from  sklearn.metrics import accuracy_score \n",
    "from sklearn.utils import as_float_array\n",
    "import csv\n",
    "import math\n",
    "import collections\n",
    "keys = {'C': 0, 'C#': 1, 'D': 2, 'D#': 3, 'E': 4, 'F': 5, \n",
    "        'F#': 6, 'G': 7, 'G#': 8, 'A': 9, 'A#': 10, 'B': 11}\n",
    "genreStrings = []\n",
    "allFeaturesMatrix = []\n",
    "allFeaturesDict = {}\n",
    "masterGenreDict = {}\n",
    "genreArrayDict = {}\n",
    "genreToCoefficients = {}\n",
    "genreDict = {}\n",
    "\n",
    "#songToGenre = {}\n",
    "\n",
    "def readMusicData(filename) :\n",
    "    # open a file\n",
    "    with open(filename) as f:\n",
    "        line = csv.reader(f)\n",
    "        # loop over each row in the file\n",
    "        rowNum = 0\n",
    "        for row in line:\n",
    "            if rowNum == 0 : \n",
    "                rowNum += 1\n",
    "                continue\n",
    "            # cast each value to a float\n",
    "            features = []\n",
    "            currFeature = 0\n",
    "            nameID = \"\"\n",
    "            for value in row :\n",
    "                if currFeature ==0:\n",
    "                    if value not in genreStrings:\n",
    "                        genreStrings.append(value)\n",
    "                if (currFeature >= 4 and currFeature <= 8) or currFeature == 10 \\\n",
    "                    or currFeature == 11 or currFeature == 13 or currFeature == 14 \\\n",
    "                        or currFeature == 16: \n",
    "                        value = float(value)\n",
    "                if currFeature == 15 : \n",
    "                    value = int(value[0])\n",
    "                if currFeature == 3 : \n",
    "                    nameID = str(value)\n",
    "                if currFeature == 9 : \n",
    "                    value = keys[value]\n",
    "                if currFeature == 12 : \n",
    "                    value = 1 if value == \"Major\" else 0\n",
    "                features.append(value)\n",
    "                currFeature += 1\n",
    "            allFeaturesDict[nameID] = features\n",
    "            allFeaturesMatrix.append(features)\n",
    "            rowNum += 1\n",
    "        # store the row into our dict\n",
    "\n",
    "def requests(name) :\n",
    "    songRequests = collections.defaultdict(None)\n",
    "    count = 0\n",
    "    with open(name,'r') as file :\n",
    "        for line in file: \n",
    "            if line==\"\\n\":\n",
    "                break\n",
    "#             print(line)\n",
    "            lines = line.split(' = c(')\n",
    "#             print(lines)\n",
    "            name = lines[0]\n",
    "            lines[1] = lines[1].replace('\\\"', \"\")\n",
    "            ids = lines[1].split(\", \")\n",
    "            ids[0] = ids[0].replace('c(', \"\")\n",
    "            ids[4] = ids[4].replace(')\\n', \"\")\n",
    "            songRequests[name] = ids\n",
    "            count += 1\n",
    "            if count == 51 : break\n",
    "    return collections.OrderedDict(sorted(songRequests.items()))\n",
    "\n",
    "def makeGenreDict(filename, genre, genreArray) :\n",
    "    # open a file\n",
    "    with open(filename) as f:\n",
    "        line = csv.reader(f)\n",
    "        # loop over each row in the file\n",
    "        rowNum = 0\n",
    "        for row in line:\n",
    "            if rowNum == 0 : \n",
    "                rowNum += 1\n",
    "                continue\n",
    "            # cast each value to a float\n",
    "            # features = []\n",
    "            currFeature = 0\n",
    "            nameID = \"\"\n",
    "            genreY = 0\n",
    "            gname = \"\"\n",
    "            for value in row :\n",
    "#                 if value==\"Good as Hell\":\n",
    "#                     print(\"ITS IN THERE SOMEWHERE\")\n",
    "                if currFeature ==0:\n",
    "#                     genre = 0\n",
    "                    gname = value\n",
    "                    if value == genre:\n",
    "                        genreY = 1\n",
    "                if currFeature == 3 : \n",
    "                    nameID = str(value)\n",
    "                currFeature+=1\n",
    "            genreDict[nameID] = str(gname)\n",
    "            genreArray.append(genreY)\n",
    "            rowNum += 1\n",
    "#extract numerical features only, with the first value as 'id'\n",
    "def sigmoid(x):\n",
    "    return 1 / (1 + math.exp(-x))\n",
    "def numericalFeaturesOnly(allFeatures, toUse = []) : \n",
    "    newFeatures = []\n",
    "    if not toUse :\n",
    "        for feature in allFeatures :\n",
    "            newFeatures.append(feature[4:])\n",
    "    else : \n",
    "        for feature in allFeatures : \n",
    "            feature = [feature[i] for i in range(len(feature)) if i in toUse]\n",
    "            newFeatures.append(feature)\n",
    "    return newFeatures\n",
    "\n",
    "def outputResults(toUse = [], average = True) :\n",
    "    necessaryDict = {}\n",
    "    totalSongs = 0\n",
    "    numIncorrect = 0 \n",
    "#     print(friends)\n",
    "    for person, songIds in friends.items() : \n",
    "#         print(person)\n",
    "        songs = []\n",
    "        for song in songIds : \n",
    "            #Using all songs\n",
    "            info = allFeaturesDict[song]\n",
    "            if not toUse : \n",
    "                songs.append(info[4:])\n",
    "                necessaryDict[song] = info[4:]\n",
    "            else : \n",
    "                songs.append([info[i] for i in range(len(info)) if i in toUse])\n",
    "                necessaryDict[song] = [info[i] for i in range(len(info)) if i in toUse]\n",
    "#             print(necessaryDict[song])\n",
    "            totalSongs+=1\n",
    "            \n",
    "        \n",
    "        \n",
    "        print(\"Songs for my friend \" + person)\n",
    "        print(\"\\t Input songs: \")\n",
    "#         print(songs)\n",
    "        for song in songIds : \n",
    "            print(\"\\t\\t\" + allFeaturesDict[song][2] + \" by \" + allFeaturesDict[song][1])\n",
    "            scores = []\n",
    "            scoresDict = {}\n",
    "#         for song in songIds:\n",
    "            j=0\n",
    "            for i in range(1, len(genreStrings)):\n",
    "#                 a = allFeaturesDict[song]\n",
    "#                 b = genreToCoefficients[genreStrings[i]]\n",
    "#                 a = map(lambda x: float(x),a)\n",
    "#                 b = map(lambda x: float(x),b)\n",
    "#                 score = a@b\n",
    "#                 print(necessaryDict[song])\n",
    "#                 print(genreToCoefficients[genreStrings[i]][0])\n",
    "                score =  as_float_array(necessaryDict[song], copy=True) @ genreToCoefficients[genreStrings[i]][0]\n",
    "                sigmoidScore = sigmoid(score + genreToModel[genreStrings[i]].intercept_)                           \n",
    "                scores.append(sigmoidScore)\n",
    "                scoresDict[sigmoidScore] = genreStrings[i]\n",
    "            j+=1\n",
    "#             print(scores)\n",
    "\n",
    "            maxScore = max(scores)\n",
    "#             print(scoresDict)\n",
    "            print(scoresDict[maxScore])\n",
    "#             print(scores[])\n",
    "            print(\"Correct genre:\")\n",
    "            print(genreDict[song])\n",
    "            print(maxScore)\n",
    "#             print(sigmoid(maxScore + genreToModel[scoresDict[maxScore]].intercept_))\n",
    "            \n",
    "            \n",
    "            if(scoresDict[maxScore]!=genreDict[song]): \n",
    "                if(genreDict[song]=='NULL'):\n",
    "                    numIncorrect-=2\n",
    "                    totalSongs-=1\n",
    "                numIncorrect+=1\n",
    "        # print \"\\t Averaged features: \"\n",
    "        # #average of all the features!\n",
    "        # for line in result : \n",
    "        #     for song in line : \n",
    "        #         print \"\\t\\t\" + allFeaturesMatrix[song][2] + \" by \" + allFeaturesMatrix[song][1]\n",
    "        # print \"\\t Nearest neighbor to individual song: \"\n",
    "#         predicted_classes = model.predict(songs)\n",
    "#         print(predicted_classes)\n",
    "#         totalSongs = 0\n",
    "        #only the nearest neighbor that is not itself!\n",
    "        # for line in result2 : \n",
    "        #     print \"\\t\\t\" + allFeaturesMatrix[line[1]][2] + \" by \" + allFeaturesMatrix[line[1]][1]\n",
    "        print(\"\\n\")\n",
    "    return (numIncorrect, totalSongs)\n",
    "\n",
    "print(\"Reading File Data!\\n\")\n",
    "# Our friend song interests. \n",
    "friends = requests('SongInput.txt')\n",
    "#populate matrix and dict with all features\n",
    "readMusicData('SpotifyFeatures.csv')\n",
    "print(genreStrings)\n",
    "print(len(genreStrings))\n",
    "\n",
    "#Feature indices, beginning at 4 and ending at 16, inclusive. BTW, 12 features total. \n",
    "#first example: all features\n",
    "# desiredFeatures = [i for i in range(4,17)]\n",
    "#second example: \"Danceability, Speechiness, Acousticness, Instrumentalness, Liveness, Valence, Loudness, and Tempo\"\n",
    "\n",
    "desiredFeatures = [4,5,8,10,11,13,14,16]\n",
    "desFeat2 = [4, 5, 7, 8, 10, 11, 13, 14, 16]\n",
    "# desFeat3 = [4, 5, 7, 8, 13]\n",
    "#just the numerical features sans artist/titles/genre/id\n",
    "numericalFeatures = numericalFeaturesOnly(allFeaturesMatrix, desFeat2)\n",
    "# model = LogisticRegression()\n",
    "# model.fit(allFeaturesMatrix, genreArray)\n",
    "# print(allFeaturesMatrix)\n",
    "genreToModel = {}\n",
    "print(\"here\")\n",
    "# genreArrays\n",
    "for i in range(1, len(genreStrings)):\n",
    "    mdl = LogisticRegression()\n",
    "    genreArray = []\n",
    "#     genreDict = {}\n",
    "    print(genreStrings[i])\n",
    "    makeGenreDict(\"SpotifyFeatures.csv\", genreStrings[i], genreArray)\n",
    "    \n",
    "#     print(genreArray)\n",
    "    fittedmdl = mdl.fit(numericalFeatures, genreArray)\n",
    "    print(genreStrings[i])\n",
    "    print(sum(genreArray))\n",
    "#     print(fittedmdl.coef_)\n",
    "    floats = as_float_array(fittedmdl.coef_, copy=True)\n",
    "    genreToCoefficients[genreStrings[i]] = floats\n",
    "    genreArrayDict[genreStrings[i]] = genreArray\n",
    "    masterGenreDict[genreStrings[i]] = genreDict\n",
    "    genreToModel[genreStrings[i]] = fittedmdl\n",
    "\n",
    "\n",
    "# predicted_classes = model.predict(X)\n",
    "# accuracy = accuracy_score(genreArray.flatten(),predicted_classes)\n",
    "# parameters = model.coef_"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "for i in range(1, len(genreStrings)):\n",
    "    print(\"Predicting for \" + genreStrings[i])\n",
    "    outputResults(genreToModel[genreStrings[i]], desiredFeatures)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "survived the loop\n",
      "Songs for my friend aarthip\n",
      "\t Input songs: \n",
      "\t\tGood as Hell by Lizzo\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.21971186264868808\n",
      "\t\tMagic In The Hamptons (feat. Lil Yachty) by Social House\n",
      "Jazz\n",
      "Correct genre:\n",
      "Pop\n",
      "0.22682753508681755\n",
      "\t\tMUSHROOM CHOCOLATE (with 6LACK) by QUIN\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.17145312477970961\n",
      "\t\tTalk by Khalid\n",
      "Rap\n",
      "Correct genre:\n",
      "Pop\n",
      "0.3661087698123463\n",
      "\t\tMillionaire (feat. Nelly) by Cash Cash\n",
      "Dance\n",
      "Correct genre:\n",
      "Dance\n",
      "0.1285846258592576\n",
      "\n",
      "\n",
      "Songs for my friend ademia\n",
      "\t Input songs: \n",
      "\t\tShaolin Monk Motherfunk by Hiatus Kaiyote\n",
      "Reggae\n",
      "Correct genre:\n",
      "R&B\n",
      "0.08625014412741858\n",
      "\t\tNerd Mountain by Kneebody\n",
      "Electronic\n",
      "Correct genre:\n",
      "NULL\n",
      "0.22518093408213266\n",
      "\t\tLingus by Snarky Puppy\n",
      "Electronic\n",
      "Correct genre:\n",
      "Jazz\n",
      "0.20954510626204764\n",
      "\t\tMy Time by Jordan Rakei\n",
      "R&B\n",
      "Correct genre:\n",
      "R&B\n",
      "0.08872832342698726\n",
      "\t\tLove Falls Down by Poppy Ajudha\n",
      "Folk\n",
      "Correct genre:\n",
      "NULL\n",
      "0.08963742774836972\n",
      "\n",
      "\n",
      "Songs for my friend aja\n",
      "\t Input songs: \n",
      "\t\tYou & Jennifer by bülow\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Indie\n",
      "0.1545149425832376\n",
      "\t\tCatch Me (feat. Naaz) by Flux Pavilion\n",
      "Ska\n",
      "Correct genre:\n",
      "Electronic\n",
      "0.1561809168270921\n",
      "\t\tLosing It by FISHER\n",
      "Electronic\n",
      "Correct genre:\n",
      "NULL\n",
      "0.6739348189702579\n",
      "\t\tLet Me Take You (feat. Jeremih) by Whethan\n",
      "Dance\n",
      "Correct genre:\n",
      "NULL\n",
      "0.17062089267300592\n",
      "\t\tEnergy (with A$AP Rocky & Sabrina Claudio) by BURNS\n",
      "Electronic\n",
      "Correct genre:\n",
      "NULL\n",
      "0.22782143566441235\n",
      "\n",
      "\n",
      "Songs for my friend alexandrah\n",
      "\t Input songs: \n",
      "\t\tCeleste by Ezra Vine\n",
      "Country\n",
      "Correct genre:\n",
      "Pop\n",
      "0.1260118526963534\n",
      "\t\tSedona by Houndmouth\n",
      "World\n",
      "Correct genre:\n",
      "Pop\n",
      "0.15072525751967847\n",
      "\t\tBeyond by Leon Bridges\n",
      "Dance\n",
      "Correct genre:\n",
      "Soul\n",
      "0.09941711725075504\n",
      "\t\tNew Theory by Washed Out\n",
      "Electronic\n",
      "Correct genre:\n",
      "Dance\n",
      "0.23268210169312786\n",
      "\t\tPurple by SAUCITO\n",
      "Dance\n",
      "Correct genre:\n",
      "NULL\n",
      "0.23815911326411737\n",
      "\n",
      "\n",
      "Songs for my friend alexb\n",
      "\t Input songs: \n",
      "\t\tWorship by MAX\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Dance\n",
      "0.41638031435167083\n",
      "\t\tTalk by Khalid\n",
      "Rap\n",
      "Correct genre:\n",
      "Pop\n",
      "0.3661087698123463\n",
      "\t\tBack to You - Tre Sera Remix by Sara Diamond\n",
      "Electronic\n",
      "Correct genre:\n",
      "NULL\n",
      "0.1368302183518203\n",
      "\t\tBeliever by Luke Christopher\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.15678534723192808\n",
      "\t\tSex n' Drugs by Abhi The Nomad\n",
      "R&B\n",
      "Correct genre:\n",
      "Hip-Hop\n",
      "0.23626326489120364\n",
      "\n",
      "\n",
      "Songs for my friend alexr\n",
      "\t Input songs: \n",
      "\t\tCreep by Radiohead\n",
      "World\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.13742932505659008\n",
      "\t\tCall Me in the Afternoon by Half Moon Run\n",
      "Ska\n",
      "Correct genre:\n",
      "Folk\n",
      "0.33026316984218584\n",
      "\t\tHummingbird by Traveller\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.3253477796898814\n",
      "\t\t7 Years by Lukas Graham\n",
      "Pop\n",
      "Correct genre:\n",
      "Pop\n",
      "0.1475041885647551\n",
      "\t\tFast Car by Tracy Chapman\n",
      "Folk\n",
      "Correct genre:\n",
      "Pop\n",
      "0.06919695393551906\n",
      "\n",
      "\n",
      "Songs for my friend allan\n",
      "\t Input songs: \n",
      "\t\tSweater Weather by The Neighbourhood\n",
      "Dance\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.20488751995444374\n",
      "\t\t92 Explorer by Post Malone\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.38206131123898185\n",
      "\t\tMALA (feat. Anuel Aa) by 6ix9ine\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Rap\n",
      "0.3580913774705301\n",
      "\t\tSpace Cadet (feat. Gunna) by Metro Boomin\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.18753796498082162\n",
      "\t\tBorrowed Love (feat. Swae Lee & WizKid) by Metro Boomin\n",
      "Comedy\n",
      "Correct genre:\n",
      "Pop\n",
      "0.04835109033417338\n",
      "\n",
      "\n",
      "Songs for my friend amandam1\n",
      "\t Input songs: \n",
      "\t\tI Don't Care (with Justin Beiber) by Ed Sheeran\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.299041610821355\n",
      "\t\tIf I Can't Have You by Shawn Mendes\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.260091037849201\n",
      "\t\tNIKES by Jake Miller\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.15149810582767392\n",
      "\t\tSixteen by Ellie Goulding\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.12205280890162086\n",
      "\t\tDo You Mean (with Ty Dolla $ign & bülow) by The Chainsmokers\n",
      "Country\n",
      "Correct genre:\n",
      "NULL\n",
      "0.08290935781985159\n",
      "\n",
      "\n",
      "Songs for my friend amandam2\n",
      "\t Input songs: \n",
      "\t\tHey Look Ma, I Made It by Panic! At The Disco\n",
      "Dance\n",
      "Correct genre:\n",
      "Pop\n",
      "0.15709305746063637\n",
      "\t\tSKINNYDIP by Jake Miller\n",
      "Country\n",
      "Correct genre:\n",
      "NULL\n",
      "0.14552816699863297\n",
      "\t\tAll My Friends by AJ Mitchell\n",
      "Dance\n",
      "Correct genre:\n",
      "Pop\n",
      "0.16540145886413932\n",
      "\t\tTalk by Khalid\n",
      "Rap\n",
      "Correct genre:\n",
      "Pop\n",
      "0.3661087698123463\n",
      "\t\tCarry On (from the Original Motion Picture \"POKEMON Detective Pikachu\") by Kygo\n",
      "Dance\n",
      "Correct genre:\n",
      "NULL\n",
      "0.06431399636645464\n",
      "\n",
      "\n",
      "Songs for my friend amar\n",
      "\t Input songs: \n",
      "\t\tKey Lime OG by Rico Nasty\n",
      "Rap\n",
      "Correct genre:\n",
      "Rap\n",
      "0.24866178581285192\n",
      "\t\tFor You by August Alsina\n",
      "World\n",
      "Correct genre:\n",
      "Dance\n",
      "0.05724633396633401\n",
      "\t\t2012 by Chris Brown\n",
      "R&B\n",
      "Correct genre:\n",
      "Dance\n",
      "0.06591805277861786\n",
      "\t\tPromises by Jhene Aiko\n",
      "Folk\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.0549928819829733\n",
      "\t\tRamriddlz by Melanincholy\n",
      "Electronic\n",
      "Correct genre:\n",
      "NULL\n",
      "0.13647165760526284\n",
      "\n",
      "\n",
      "Songs for my friend andreab\n",
      "\t Input songs: \n",
      "\t\tWritten in the Sand by Old Dominion\n",
      "Jazz\n",
      "Correct genre:\n",
      "Country\n",
      "0.14339085028199006\n",
      "\t\tSlow Dance In A Parking Lot by Jordan Davis\n",
      "Country\n",
      "Correct genre:\n",
      "Pop\n",
      "0.11354258703123332\n",
      "\t\tUnforgettable by Thomas Rhett\n",
      "Reggae\n",
      "Correct genre:\n",
      "Country\n",
      "0.19783946581530581\n",
      "\t\tNowhere Fast by Old Dominion\n",
      "Folk\n",
      "Correct genre:\n",
      "Country\n",
      "0.12362600929592038\n",
      "\t\tBreak up in the End by Cole Swindell\n",
      "Folk\n",
      "Correct genre:\n",
      "Country\n",
      "0.11227234449853771\n",
      "\n",
      "\n",
      "Songs for my friend andrese\n",
      "\t Input songs: \n",
      "\t\tHay Amores by Shakira\n",
      "Movie\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2418147329670837\n",
      "\t\tLa Puerta de Alcalá by Ana Belén & Víctor Manuel\n",
      "Country\n",
      "Correct genre:\n",
      "NULL\n",
      "0.13830337827720415\n",
      "\t\tPiano Man by Billy Joel\n",
      "Folk\n",
      "Correct genre:\n",
      "Folk\n",
      "0.15850124546864655\n",
      "\t\t'39 - Remastered 2011 by Queen\n",
      "Country\n",
      "Correct genre:\n",
      "Rock\n",
      "0.09604715322044949\n",
      "\t\tSomebody To Love by Queen\n",
      "Country\n",
      "Correct genre:\n",
      "Rock\n",
      "0.062440070211352824\n",
      "\n",
      "\n",
      "Songs for my friend aprilb\n",
      "\t Input songs: \n",
      "\t\tI Don't Care (with Justin Beiber) by Ed Sheeran\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.299041610821355\n",
      "\t\tMamma Mia by ABBA\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.2445455946246029\n",
      "\t\tUpper West Side by King Princess\n",
      "Reggae\n",
      "Correct genre:\n",
      "Dance\n",
      "0.14010232517475443\n",
      "\t\tWho Says by John Mayer\n",
      "World\n",
      "Correct genre:\n",
      "Pop\n",
      "0.08175807190771317\n",
      "\t\tUnforgettable by Thomas Rhett\n",
      "Reggae\n",
      "Correct genre:\n",
      "Country\n",
      "0.19783946581530581\n",
      "\n",
      "\n",
      "Songs for my friend beatricef\n",
      "\t Input songs: \n",
      "\t\tGloria by Tierra Whack\n",
      "Reggae\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.2314445890341383\n",
      "\t\tShe Don't Use Jelly by The Flaming Lips\n",
      "Ska\n",
      "Correct genre:\n",
      "Blues\n",
      "0.1033073415857059\n",
      "\t\tAmor, Amor de Mis Amores by Natalia Lafourcade\n",
      "Reggae\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.2605059300445355\n",
      "\t\tSisyphus by Andrew Bird\n",
      "Dance\n",
      "Correct genre:\n",
      "Pop\n",
      "0.12566151872037395\n",
      "\t\tThe Barrel by Aldous Harding\n",
      "Jazz\n",
      "Correct genre:\n",
      "Pop\n",
      "0.17108716723642536\n",
      "\n",
      "\n",
      "Songs for my friend brycej\n",
      "\t Input songs: \n",
      "\t\tMiss Shiney by Kaiit\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.15802541378075818\n",
      "\t\tYou & Me by Marc E. Bassy\n",
      "Reggae\n",
      "Correct genre:\n",
      "Dance\n",
      "0.15698918205310639\n",
      "\t\tMomma I Hit A Lick (feat. Kendrick Lamar) by 2 Chainz\n",
      "Rap\n",
      "Correct genre:\n",
      "Pop\n",
      "0.30209240997010306\n",
      "\t\tFree Smoke by Drake\n",
      "Rap\n",
      "Correct genre:\n",
      "Pop\n",
      "0.19630612220717164\n",
      "\t\t6 Foot 7 Foot by Lil Wayne\n",
      "Ska\n",
      "Correct genre:\n",
      "Pop\n",
      "0.241973278626151\n",
      "\n",
      "\n",
      "Songs for my friend brycej2\n",
      "\t Input songs: \n",
      "\t\tA Milli by Lil Wayne\n",
      "Reggae\n",
      "Correct genre:\n",
      "Pop\n",
      "0.16142027860741165\n",
      "\t\tNobody but Me by Michael Bublè\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2873115943331988\n",
      "\t\tJump Out The Window by Big Sean\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.15427212063489573\n",
      "\t\tGod is a woman by Ariana Grande\n",
      "Dance\n",
      "Correct genre:\n",
      "Pop\n",
      "0.13638268936085365\n",
      "\t\tNASA by Ariana Grande\n",
      "R&B\n",
      "Correct genre:\n",
      "Pop\n",
      "0.11180884137821408\n",
      "\n",
      "\n",
      "Songs for my friend camilav\n",
      "\t Input songs: \n",
      "\t\tBetter Not (with Wafia) by Louis The Child\n",
      "Pop\n",
      "Correct genre:\n",
      "Pop\n",
      "0.24976002233708666\n",
      "\t\tOne Kiss (with Dua Lipa) by Calvin Harris\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.3486812224480331\n",
      "\t\tGirls Like You (feat. Cardi B) by Maroon 5\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.24636417267401275\n",
      "\t\tYou Make It Easy by Jason Aldean\n",
      "Country\n",
      "Correct genre:\n",
      "Country\n",
      "0.15153496919460144\n",
      "\t\tSay You Won't Let Go by James Arthur\n",
      "Movie\n",
      "Correct genre:\n",
      "Pop\n",
      "0.10640066706771133\n",
      "\n",
      "\n",
      "Songs for my friend caroq\n",
      "\t Input songs: \n",
      "\t\tBrilliant Bitch by SAINt JHN\n",
      "Rap\n",
      "Correct genre:\n",
      "Rap\n",
      "0.17645958735351927\n",
      "\t\tBig Wheels by Kevin Abstract\n",
      "Electronic\n",
      "Correct genre:\n",
      "NULL\n",
      "0.16256288561582238\n",
      "\t\tJuice by Lizzo\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.3615951228810767\n",
      "\t\tCampfire by Aminé\n",
      "Reggae\n",
      "Correct genre:\n",
      "Pop\n",
      "0.38053615711186367\n",
      "\t\tEnergy (with A$AP Rocky & Sabrina Claudio) by BURNS\n",
      "Electronic\n",
      "Correct genre:\n",
      "NULL\n",
      "0.22782143566441235\n",
      "\n",
      "\n",
      "Songs for my friend caseyb\n",
      "\t Input songs: \n",
      "\t\tPlay That Song by Train\n",
      "Alternative\n",
      "Correct genre:\n",
      "Dance\n",
      "0.17086550046002258\n",
      "\t\tMeant to Be (feat. Florida Georgia Line) by Bebe Rexha\n",
      "Dance\n",
      "Correct genre:\n",
      "Pop\n",
      "0.09629362180078957\n",
      "\t\tOne Man Band by Old Dominion\n",
      "Folk\n",
      "Correct genre:\n",
      "Country\n",
      "0.1370211514069082\n",
      "\t\tOld Town Road - Remix by Lil Nas X\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.28507472591008404\n",
      "\t\tGateway Love by Thomas Rhett\n",
      "Reggae\n",
      "Correct genre:\n",
      "Country\n",
      "0.14959064971030328\n",
      "\n",
      "\n",
      "Songs for my friend emilyr\n",
      "\t Input songs: \n",
      "\t\tbad guy by Billie Eilish\n",
      "Reggae\n",
      "Correct genre:\n",
      "Pop\n",
      "0.08746961219809304\n",
      "\t\tbloodline by Ariana Grande\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.17195045184182198\n",
      "\t\tSolo (feat. Demi Lovato) by Clean Bandit\n",
      "Dance\n",
      "Correct genre:\n",
      "Pop\n",
      "0.19276498975424763\n",
      "\t\tLost In Japan - Recorded at Spotify Studios NYC by Shawn Mendes\n",
      "Movie\n",
      "Correct genre:\n",
      "Dance\n",
      "0.12803642866868367\n",
      "\t\tWoman Like Me (feat. Nicki Minaj) by Little Mix\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.3891103309466361\n",
      "\n",
      "\n",
      "Songs for my friend gabbyc\n",
      "\t Input songs: \n",
      "\t\tGo Loko by YG\n",
      "Pop\n",
      "Correct genre:\n",
      "NULL\n",
      "0.17629936623637868\n",
      "\t\tHigh Horse by Kacey Musgraves\n",
      "Reggae\n",
      "Correct genre:\n",
      "Pop\n",
      "0.2380750314614195\n",
      "\t\tLosing It by FISHER\n",
      "Electronic\n",
      "Correct genre:\n",
      "NULL\n",
      "0.6739348189702579\n",
      "\t\tAll Dolled-Up in Straps by The National\n",
      "Soundtrack\n",
      "Correct genre:\n",
      "NULL\n",
      "0.3372933688979058\n",
      "\t\tYou Were Right by Rüfüs du Sol\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.15962461285905322\n",
      "\n",
      "\n",
      "Songs for my friend gabea\n",
      "\t Input songs: \n",
      "\t\tHow Long? by Vampire Weekend\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2647929609835118\n",
      "\t\tI Need Help! by Fritz and the Tantrums\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2275732288666685\n",
      "\t\tMissed Connection by The Head and the Heart\n",
      "Dance\n",
      "Correct genre:\n",
      "NULL\n",
      "0.13630195660021313\n",
      "\t\tJet Black (feat. Brandy) by Anderson .Paak\n",
      "Rap\n",
      "Correct genre:\n",
      "NULL\n",
      "0.1550884896177251\n",
      "\t\tFade Out by CAPYAC\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.18857096504947754\n",
      "\n",
      "\n",
      "Songs for my friend gungukk\n",
      "\t Input songs: \n",
      "\t\tSunday Morning (feat. Josie Dunne) by Matoma\n",
      "Dance\n",
      "Correct genre:\n",
      "Dance\n",
      "0.10053626197246823\n",
      "\t\tPower by Hardwell\n",
      "Electronic\n",
      "Correct genre:\n",
      "Dance\n",
      "0.18815587480100388\n",
      "\t\t4th Dimension by KIDS SEE GHOSTS\n",
      "Reggae\n",
      "Correct genre:\n",
      "Pop\n",
      "0.18998114019779713\n",
      "\t\t1, 2, 3 (feat. Jason Derulo & De La Ghetto) by Sofia Reyes\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Dance\n",
      "0.42865578654663666\n",
      "\t\tBella Ciao by Hardwell\n",
      "Electronic\n",
      "Correct genre:\n",
      "Dance\n",
      "0.26179904138704907\n",
      "\n",
      "\n",
      "Songs for my friend inesn1\n",
      "\t Input songs: \n",
      "\t\tAlguien by Siempre Asi\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.14099567490147574\n",
      "\t\tPenelope by Joan Manuel Serrat\n",
      "Folk\n",
      "Correct genre:\n",
      "NULL\n",
      "0.15987095949116162\n",
      "\t\tKodachrome by Paul Simon\n",
      "Ska\n",
      "Correct genre:\n",
      "Folk\n",
      "0.28170401375825194\n",
      "\t\tToday - Live at Five Seasons Center, Cedar Rapids, IA - December 1987 by John Denver\n",
      "Opera\n",
      "Correct genre:\n",
      "Folk\n",
      "0.2949106981755319\n",
      "\t\tI Wish You Love by Natalie Cole\n",
      "Opera\n",
      "Correct genre:\n",
      "NULL\n",
      "0.3653507954310019\n",
      "\n",
      "\n",
      "Songs for my friend inesn2\n",
      "\t Input songs: \n",
      "\t\tPerfect Symphony (Ed Sheeran & Andrea Bocelli) by Ed Sheeran\n",
      "Pop\n",
      "Correct genre:\n",
      "Pop\n",
      "0.1745564891805494\n",
      "\t\tWhen We Were Young by Adele\n",
      "World\n",
      "Correct genre:\n",
      "Pop\n",
      "0.11019270703255817\n",
      "\t\tComo Han Pasado los Años by Rocio Dúrcal\n",
      "Country\n",
      "Correct genre:\n",
      "NULL\n",
      "0.13265261841302753\n",
      "\t\tA Mi Manera - Tema Remasterizado by Vicente Fernandez\n",
      "Movie\n",
      "Correct genre:\n",
      "NULL\n",
      "0.23714792258777326\n",
      "\t\tPor el Resto de Mi Vida by Andrés Cepeda\n",
      "Folk\n",
      "Correct genre:\n",
      "NULL\n",
      "0.0714691293596321\n",
      "\n",
      "\n",
      "Songs for my friend jessicay\n",
      "\t Input songs: \n",
      "\t\tKLINK by Smino\n",
      "Reggae\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.26045941562632774\n",
      "\t\tbad guy by Billie Eilish\n",
      "Reggae\n",
      "Correct genre:\n",
      "Pop\n",
      "0.08746961219809304\n",
      "\t\tMake It Better (feat. Smokey Robinson) by Anderson .Paak\n",
      "Dance\n",
      "Correct genre:\n",
      "NULL\n",
      "0.1534021186745826\n",
      "\t\tTopdown by Channel Tres\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.14407511630553874\n",
      "\t\tSo into You by Tamia\n",
      "Reggae\n",
      "Correct genre:\n",
      "Dance\n",
      "0.23585881531262984\n",
      "\n",
      "\n",
      "Songs for my friend jjr\n",
      "\t Input songs: \n",
      "\t\tFloating (feat. 21 Savage) by ScHoolboy Q\n",
      "Rap\n",
      "Correct genre:\n",
      "NULL\n",
      "0.3943541024420787\n",
      "\t\tGo Loko by YG\n",
      "Pop\n",
      "Correct genre:\n",
      "NULL\n",
      "0.17629936623637868\n",
      "\t\tSwervin (feat. 6ix9ine) by A Boogie Wit da Hoodie\n",
      "Rap\n",
      "Correct genre:\n",
      "Rap\n",
      "0.08662772512686415\n",
      "\t\tThe Ways (with Swae Lee) by Khalid\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.1452599978064649\n",
      "\t\tSanguine Paradise by Lil Uzi Vert\n",
      "Rap\n",
      "Correct genre:\n",
      "NULL\n",
      "0.15162425701854726\n",
      "\n",
      "\n",
      "Songs for my friend juann\n",
      "\t Input songs: \n",
      "\t\tTalk Is Cheap by Nick Murphy / Chet Faker\n",
      "Pop\n",
      "Correct genre:\n",
      "Indie\n",
      "0.04861861364971953\n",
      "\t\tStronger by Kanye West\n",
      "Reggae\n",
      "Correct genre:\n",
      "Pop\n",
      "0.06954751672076338\n",
      "\t\tSwimming Pools (Drank) - Extended Version by Kendrick Lamar\n",
      "Rap\n",
      "Correct genre:\n",
      "Pop\n",
      "0.1701179265398439\n",
      "\t\tR u a Freak by Snoop Dogg\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.11708300741398148\n",
      "\t\tMr. Carter by Lil Wayne\n",
      "Ska\n",
      "Correct genre:\n",
      "Pop\n",
      "0.05389134483186522\n",
      "\n",
      "\n",
      "Songs for my friend jupip\n",
      "\t Input songs: \n",
      "\t\tWalls Down by Memba\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.14543232952136784\n",
      "\t\tPursuit Of Happiness (Nightmare) by Kid Cudi\n",
      "World\n",
      "Correct genre:\n",
      "Pop\n",
      "0.09350988518064642\n",
      "\t\tJewel by Flume\n",
      "World\n",
      "Correct genre:\n",
      "NULL\n",
      "0.3242794333351409\n",
      "\t\tRacks In The Middle (feat. Roddy Ricch and Hit-Boy) by Nipsey Hussle\n",
      "Reggae\n",
      "Correct genre:\n",
      "Pop\n",
      "0.10901700508694069\n",
      "\t\tStartender (feat. Offset and Tyga) by A Boogie Wit da Hoodie\n",
      "Pop\n",
      "Correct genre:\n",
      "Rap\n",
      "0.1708471444227496\n",
      "\n",
      "\n",
      "Songs for my friend kareem\n",
      "\t Input songs: \n",
      "\t\tlava by still woozy\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.06607428528215052\n",
      "\t\tsan francisco street by sun rai\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.16307145763826555\n",
      "\t\tlying has to stop by soft ray\n",
      "Movie\n",
      "Correct genre:\n",
      "NULL\n",
      "0.16462539138089005\n",
      "\t\tWarm (feat. Mia) by Dre'es\n",
      "Movie\n",
      "Correct genre:\n",
      "Soul\n",
      "0.12022478768454402\n",
      "\t\tpatience by Tame Impala\n",
      "Ska\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2304114714408034\n",
      "\n",
      "\n",
      "Songs for my friend kayla\n",
      "\t Input songs: \n",
      "\t\tGoing Gets Tough by The Growlers\n",
      "Country\n",
      "Correct genre:\n",
      "Indie\n",
      "0.1680773317790634\n",
      "\t\tCut Your Bangs by Girlpool\n",
      "Folk\n",
      "Correct genre:\n",
      "Folk\n",
      "0.2317812327716832\n",
      "\t\tStella Blue by Local Natives\n",
      "World\n",
      "Correct genre:\n",
      "Folk\n",
      "0.1335664932295297\n",
      "\t\tTungs by The Frights\n",
      "Reggae\n",
      "Correct genre:\n",
      "Indie\n",
      "0.06438453923794199\n",
      "\t\tFiguring It Out by SWMRS\n",
      "Ska\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.2317826408473438\n",
      "\n",
      "\n",
      "Songs for my friend kyleek\n",
      "\t Input songs: \n",
      "\t\tDynamite by Taio Cruz\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.26384874446821555\n",
      "\t\tFire Burning by Sean Kingston\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Dance\n",
      "0.4727681618750073\n",
      "\t\tOld Town Road - Remix by Lil Nas X\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.28507472591008404\n",
      "\t\tAll Star by Smash Mouth\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.21909780241904991\n",
      "\t\tMan's Not Hot by Big Shaq\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.5438653830268476\n",
      "\n",
      "\n",
      "Songs for my friend liaml\n",
      "\t Input songs: \n",
      "\t\tI Don't Care by NAV\n",
      "Rap\n",
      "Correct genre:\n",
      "Rap\n",
      "0.154980668991265\n",
      "\t\t7am by Lil Uzi Vert\n",
      "Pop\n",
      "Correct genre:\n",
      "Pop\n",
      "0.05783270133647774\n",
      "\t\tCountry T by FMG\n",
      "Rap\n",
      "Correct genre:\n",
      "NULL\n",
      "0.11456069878394856\n",
      "\t\tBANG! by Trippie Redd\n",
      "Country\n",
      "Correct genre:\n",
      "Rap\n",
      "0.085065518390484\n",
      "\t\tDid That Did That by Yung Bans\n",
      "Electronic\n",
      "Correct genre:\n",
      "Hip-Hop\n",
      "0.3087164424801692\n",
      "\n",
      "\n",
      "Songs for my friend maiab\n",
      "\t Input songs: \n",
      "\t\tHarmony Hall by Vampire Weekend\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.11768852204608439\n",
      "\t\tLate Night Feelings by Lykke Li and Mark Ronson\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.11998561237919898\n",
      "\t\tLike a girl by Lizzo\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.19745367817009687\n",
      "\t\tMoon River by Frank Ocean\n",
      "Opera\n",
      "Correct genre:\n",
      "Soul\n",
      "0.30332849410581536\n",
      "\t\tSaturdays (feat. HAIM) by Twin Wild\n",
      "Ska\n",
      "Correct genre:\n",
      "Dance\n",
      "0.19106192494558383\n",
      "\n",
      "\n",
      "Songs for my friend mimami\n",
      "\t Input songs: \n",
      "\t\tAdios, Chico de MI Barrio by Tormenta\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.28833922726680083\n",
      "\t\tHay Amores by Shakira\n",
      "Movie\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2418147329670837\n",
      "\t\tNo Basta by Franco de Vita\n",
      "World\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2133364325549328\n",
      "\t\tA Mi Manera - Tema Remasterizado by Vicente Fernandez\n",
      "Movie\n",
      "Correct genre:\n",
      "NULL\n",
      "0.23714792258777326\n",
      "\t\tPor el Resto de Mi Vida by Andrés Cepeda\n",
      "Folk\n",
      "Correct genre:\n",
      "NULL\n",
      "0.0714691293596321\n",
      "\n",
      "\n",
      "Songs for my friend nevc\n",
      "\t Input songs: \n",
      "\t\tPower Over Me by Dermot Kennedy\n",
      "Ska\n",
      "Correct genre:\n",
      "Folk\n",
      "0.15813195677161596\n",
      "\t\tTruth Hurts by Lizzo\n",
      "Pop\n",
      "Correct genre:\n",
      "Pop\n",
      "0.21998398853856446\n",
      "\t\tStop This Train by John Mayer\n",
      "Folk\n",
      "Correct genre:\n",
      "Pop\n",
      "0.09174888051128885\n",
      "\t\tEasily by Bruno Major\n",
      "R&B\n",
      "Correct genre:\n",
      "Pop\n",
      "0.17803213364795936\n",
      "\t\tPoison by Brent Faiyaz\n",
      "Folk\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.08909512075988389\n",
      "\n",
      "\n",
      "Songs for my friend nickor\n",
      "\t Input songs: \n",
      "\t\tBe with me by Jordy\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.20758888830201297\n",
      "\t\tGhosts by The Presets\n",
      "Country\n",
      "Correct genre:\n",
      "Electronic\n",
      "0.09162512762967741\n",
      "\t\tTalia by King Princess\n",
      "World\n",
      "Correct genre:\n",
      "Pop\n",
      "0.07424285475548749\n",
      "\t\t1922 by Box the Oxford\n",
      "Ska\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2368609507650672\n",
      "\t\tPolaroid by Jonas Blue\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.1768962054999197\n",
      "\n",
      "\n",
      "Songs for my friend ozan\n",
      "\t Input songs: \n",
      "\t\tRudy by Rostam\n",
      "Pop\n",
      "Correct genre:\n",
      "Folk\n",
      "0.04108744092162013\n",
      "\t\tHow Long? by Vampire Weekend\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2647929609835118\n",
      "\t\tPosing in Bondage by Japanese Breakfast\n",
      "Jazz\n",
      "Correct genre:\n",
      "NULL\n",
      "0.37608202659291123\n",
      "\t\tCellophane by FKA Twigs\n",
      "Movie\n",
      "Correct genre:\n",
      "NULL\n",
      "0.13509871748865115\n",
      "\t\tStatic Buzz by Snail Mail\n",
      "Electronic\n",
      "Correct genre:\n",
      "Folk\n",
      "0.08825420135718713\n",
      "\n",
      "\n",
      "Songs for my friend richardl1\n",
      "\t Input songs: \n",
      "\t\tThe Funeral by Band of Horses\n",
      "World\n",
      "Correct genre:\n",
      "Pop\n",
      "0.19599152330406222\n",
      "\t\tOut in the Country by Natural Child\n",
      "Movie\n",
      "Correct genre:\n",
      "Folk\n",
      "0.20067482676275544\n",
      "\t\tTemple by Kings of Leon\n",
      "Ska\n",
      "Correct genre:\n",
      "Indie\n",
      "0.08568430861961897\n",
      "\t\tCASTLE OF GLASS by Linkin Park\n",
      "Ska\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.16783769809885868\n",
      "\t\tLadykiller by The Horrible Crowes\n",
      "World\n",
      "Correct genre:\n",
      "NULL\n",
      "0.12831572297616795\n",
      "\n",
      "\n",
      "Songs for my friend richardl2\n",
      "\t Input songs: \n",
      "\t\t…If You See California by Chris Robinson & The New Earth Mud\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.21888120272762732\n",
      "\t\tDance Me A Number by The Steepwater Band\n",
      "Ska\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2566448111377693\n",
      "\t\tWave of Mutilation (UK Surf) by Pixies\n",
      "Reggae\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.22586153239977014\n",
      "\t\tSeasons (Waiting On You) by Future Islands\n",
      "Electronic\n",
      "Correct genre:\n",
      "Dance\n",
      "0.19095279289764422\n",
      "\t\tThe Kill by Thirty Seconds To Mars\n",
      "Ska\n",
      "Correct genre:\n",
      "Pop\n",
      "0.2552429210873317\n",
      "\n",
      "\n",
      "Songs for my friend richardl3\n",
      "\t Input songs: \n",
      "\t\tLos Ageless by St. Vincent\n",
      "Dance\n",
      "Correct genre:\n",
      "Pop\n",
      "0.10634364601386027\n",
      "\t\tPeach Pit by Peach Pit\n",
      "Dance\n",
      "Correct genre:\n",
      "Indie\n",
      "0.12285971950107569\n",
      "\t\tNo Halo by Kevin Morby\n",
      "Jazz\n",
      "Correct genre:\n",
      "Folk\n",
      "0.17544329269030184\n",
      "\t\tHot Thoughts by Spoon\n",
      "Electronic\n",
      "Correct genre:\n",
      "Dance\n",
      "0.20729036229694997\n",
      "\t\tDown Down The Deep River  by Okkervil River\n",
      "Ska\n",
      "Correct genre:\n",
      "NULL\n",
      "0.16462002478204177\n",
      "\n",
      "\n",
      "Songs for my friend ruthl\n",
      "\t Input songs: \n",
      "\t\tRiver by Leon Bridges\n",
      "Folk\n",
      "Correct genre:\n",
      "Soul\n",
      "0.14148797235390706\n",
      "\t\tMiles Apart by Nick Wilson\n",
      "Folk\n",
      "Correct genre:\n",
      "Folk\n",
      "0.17731264795025792\n",
      "\t\tRobotics by ZaeHD & CD\n",
      "Rap\n",
      "Correct genre:\n",
      "NULL\n",
      "0.5545482782434183\n",
      "\t\tCollide by Howie Day\n",
      "Country\n",
      "Correct genre:\n",
      "Pop\n",
      "0.09423045938433171\n",
      "\t\tWhat Do I Know? by Ed Sheeran\n",
      "Reggae\n",
      "Correct genre:\n",
      "Pop\n",
      "0.40467917030964856\n",
      "\n",
      "\n",
      "Songs for my friend samd\n",
      "\t Input songs: \n",
      "\t\tReaper by Sia\n",
      "Dance\n",
      "Correct genre:\n",
      "Dance\n",
      "0.16238109452390684\n",
      "\t\tBefore I Let Go - Homecoming Live Bonus Track by Beyoncé\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.14888150974706518\n",
      "\t\tTil I Get Found by Marc E. Bassy\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Dance\n",
      "0.14503317140615557\n",
      "\t\tTwo Wrongs by Absofacto\n",
      "Jazz\n",
      "Correct genre:\n",
      "Indie\n",
      "0.14186183044425799\n",
      "\t\tEvil Twin by KRS-One\n",
      "R&B\n",
      "Correct genre:\n",
      "Soul\n",
      "0.12733841321453632\n",
      "\n",
      "\n",
      "Songs for my friend samm\n",
      "\t Input songs: \n",
      "\t\tNoBody Else (feat. Nick Cannon, Ty Dolla $ign and Jacquees) by Ncredible Gang\n",
      "Reggae\n",
      "Correct genre:\n",
      "NULL\n",
      "0.4002329778053883\n",
      "\t\tGo Loko by YG\n",
      "Pop\n",
      "Correct genre:\n",
      "NULL\n",
      "0.17629936623637868\n",
      "\t\tJuicy by Doja Cat\n",
      "Dance\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.26946999868421373\n",
      "\t\tMy Bad by Khalid\n",
      "Jazz\n",
      "Correct genre:\n",
      "Pop\n",
      "0.07014880064766926\n",
      "\t\twhen the party's over by Billie Eilish\n",
      "Opera\n",
      "Correct genre:\n",
      "NULL\n",
      "0.3674764237226856\n",
      "\n",
      "\n",
      "Songs for my friend saurenk\n",
      "\t Input songs: \n",
      "\t\tCold Room by Fit For a King\n",
      "Ska\n",
      "Correct genre:\n",
      "NULL\n",
      "0.2163851472675945\n",
      "\t\tLove Always, by The Artificials\n",
      "Electronic\n",
      "Correct genre:\n",
      "NULL\n",
      "0.316389938113451\n",
      "\t\tSafehaven by Erra\n",
      "Ska\n",
      "Correct genre:\n",
      "NULL\n",
      "0.15634540391179777\n",
      "\t\tHead Hunter by Dance Gavin Dance\n",
      "Ska\n",
      "Correct genre:\n",
      "NULL\n",
      "0.23769456899119545\n",
      "\t\tGravity by Wage War\n",
      "Ska\n",
      "Correct genre:\n",
      "NULL\n",
      "0.22107452987855067\n",
      "\n",
      "\n",
      "Songs for my friend skylart\n",
      "\t Input songs: \n",
      "\t\tThe Ways (with Swae Lee) by Khalid\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.1452599978064649\n",
      "\t\tcoffee by Miguel\n",
      "World\n",
      "Correct genre:\n",
      "Dance\n",
      "0.11769371804036172\n",
      "\t\tFrom a Distance by Russ\n",
      "Jazz\n",
      "Correct genre:\n",
      "Pop\n",
      "0.15797858100246515\n",
      "\t\tPeace Of Mind by PARTYNEXTDOOR\n",
      "Pop\n",
      "Correct genre:\n",
      "R&B\n",
      "0.24033880439163832\n",
      "\t\tLet's Fall in Love for the Night by FINNEAS\n",
      "Pop\n",
      "Correct genre:\n",
      "Pop\n",
      "0.11041173431348342\n",
      "\n",
      "\n",
      "Songs for my friend tiffany\n",
      "\t Input songs: \n",
      "\t\tWicked Games by The Weeknd\n",
      "Dance\n",
      "Correct genre:\n",
      "Pop\n",
      "0.18951839878164334\n",
      "\t\tDespacito - Remix by Luis Fonsi\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.18803056281773067\n",
      "\t\tSkyfall - Full Length by Adele\n",
      "World\n",
      "Correct genre:\n",
      "Pop\n",
      "0.16120843953681227\n",
      "\t\tCaro by Bad Bunny\n",
      "Pop\n",
      "Correct genre:\n",
      "Reggaeton\n",
      "0.09034042505216695\n",
      "\t\tDo Not Disturb by Drake\n",
      "Rap\n",
      "Correct genre:\n",
      "Pop\n",
      "0.22893071952399136\n",
      "\n",
      "\n",
      "Songs for my friend valeria\n",
      "\t Input songs: \n",
      "\t\tTruth Hurts by Lizzo\n",
      "Pop\n",
      "Correct genre:\n",
      "Pop\n",
      "0.21998398853856446\n",
      "\t\tGoing Bad (feat. Drake) by Meek Mill\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.18640875056224776\n",
      "\t\tWho Do You Love (with 5 Seconds of Summer) by The Chainsmokers\n",
      "Dance\n",
      "Correct genre:\n",
      "Pop\n",
      "0.11987240068019063\n",
      "\t\tAct Up by City Girls\n",
      "Rap\n",
      "Correct genre:\n",
      "NULL\n",
      "0.48309425499191383\n",
      "\t\tHypnotize - 2014 Remastered Version by The Notorious B.I.G.\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "Pop\n",
      "0.3685241996369682\n",
      "\n",
      "\n",
      "Songs for my friend yvese\n",
      "\t Input songs: \n",
      "\t\tSummer Friends (feat. Jeremih & Francis & The Lights) by Chance the Rapper\n",
      "Movie\n",
      "Correct genre:\n",
      "Pop\n",
      "0.061803760647941026\n",
      "\t\tChange by J. Cole\n",
      "Pop\n",
      "Correct genre:\n",
      "Pop\n",
      "0.037844014751181085\n",
      "\t\tPRETTY by Dave B.\n",
      "Pop\n",
      "Correct genre:\n",
      "NULL\n",
      "0.11249509128556694\n",
      "\t\tWat's Wrong (feat. Zacari & Kendrick Lamar) by Isaiah Rashad\n",
      "Rap\n",
      "Correct genre:\n",
      "Pop\n",
      "0.10865295806398445\n",
      "\t\tChurch / Liquor Store by Saba\n",
      "Reggae\n",
      "Correct genre:\n",
      "Alternative\n",
      "0.21815603356447813\n",
      "\n",
      "\n",
      "Songs for my friend zoev\n",
      "\t Input songs: \n",
      "\t\tTreat You Better by Rüfüs du Sol\n",
      "Pop\n",
      "Correct genre:\n",
      "NULL\n",
      "0.12284096967958374\n",
      "\t\tocean eyes by Billie Eilish\n",
      "Folk\n",
      "Correct genre:\n",
      "Pop\n",
      "0.156219251076336\n",
      "\t\tNever Go Back by Dennis Lloyd\n",
      "Reggae\n",
      "Correct genre:\n",
      "Pop\n",
      "0.14763057963191076\n",
      "\t\tDeceiver by Chris Lake\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.29516729966349103\n",
      "\t\tDeceiver by Chris Lake\n",
      "Reggaeton\n",
      "Correct genre:\n",
      "NULL\n",
      "0.29516729966349103\n",
      "\n",
      "\n",
      "58\n",
      "164\n",
      "0.35365853658536583\n"
     ]
    }
   ],
   "source": [
    "print(\"survived the loop\")\n",
    "# print(genreToCoefficients)\n",
    "numIncorrectClass = 0\n",
    "totalClassified = 0\n",
    "\n",
    "numInc, totalUpdate = outputResults(desFeat2)\n",
    "totalClassified += totalUpdate\n",
    "numIncorrectClass += numInc\n",
    "print(numIncorrectClass)\n",
    "print(totalClassified)\n",
    "\n",
    "# print(numIncorrect)\n",
    "print(float(numIncorrectClass)/float(totalClassified))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
